// Package skill renders the canonical Agent skill folder from the embedded
// schema and a set of markdown templates.
//
// The `llm-report-html skill` CLI subcommand wraps Render. The skill folder
// (`.claude/skills/llm-report-html/`) is the project's primary deliverable;
// see /README.md.
//
// Single source of truth contract:
//   - Surface catalog comes from internal/schema/schema.json `x-surface-catalog`
//     plus per-surface examples in `$defs/section.<type>.examples`.
//   - Operator catalog comes from `x-jsonlogic-operators`.
//   - Mistakes catalog comes from `x-presentation-notes`.
// Templates live alongside this file (//go:embed templates/*.tmpl.md) and
// have no other dependencies.
package skill

import (
	"bytes"
	"embed"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/yansir/llm-report-html/internal/schema"
	"github.com/yansir/llm-report-html/recipes"
)

//go:embed templates/*.tmpl.md
var templates embed.FS

const generatedHeader = "<!-- AUTO-GENERATED by `make skill`. Do not edit. Source: internal/skill/templates/. -->\n\n"

// Render writes the entire skill folder (SKILL.md + references/) to outDir.
// Caller is responsible for the assets/recipes mirror (Makefile does that).
func Render(outDir string) error {
	data, err := buildContext()
	if err != nil {
		return err
	}

	plan := []struct {
		template string
		out      string
		header   bool // false for SKILL.md (frontmatter must be first byte)
	}{
		{"skill.tmpl.md", "SKILL.md", false},
		{"composition.tmpl.md", "references/composition.md", true},
		{"surfaces.tmpl.md", "references/surfaces.md", true},
		{"operators.tmpl.md", "references/operators.md", true},
		{"reactivity.tmpl.md", "references/reactivity.md", true},
		{"mistakes.tmpl.md", "references/mistakes.md", true},
		{"type-bindings.tmpl.md", "references/type-bindings.md", true},
	}

	for _, p := range plan {
		out, err := renderOne(p.template, data)
		if err != nil {
			return fmt.Errorf("render %s: %w", p.template, err)
		}
		full := filepath.Join(outDir, p.out)
		if err := os.MkdirAll(filepath.Dir(full), 0755); err != nil {
			return err
		}
		body := out
		if p.header {
			body = generatedHeader + out
		}
		if err := os.WriteFile(full, []byte(body), 0644); err != nil {
			return fmt.Errorf("write %s: %w", full, err)
		}
	}
	return nil
}

// RenderSkillMD returns just the SKILL.md content (for `--stdout`).
func RenderSkillMD() (string, error) {
	data, err := buildContext()
	if err != nil {
		return "", err
	}
	return renderOne("skill.tmpl.md", data)
}

// ─── template context ───────────────────────────────────────────────────

type ctx struct {
	SurfaceCount      int
	RecipeCount       int
	Encodings         []surfaceRow
	Layouts           []surfaceRow
	Operators         []operatorRow
	PresentationNotes []noteRow
}

type surfaceRow struct {
	Name    string
	Usage   string
	Fields  []string
	Example string // pretty-printed JSON (no leading whitespace)
}

type operatorRow struct {
	Name    string
	Args    []string
	Doc     string
	Example string
}

type noteRow struct {
	Title string
	Body  string
}

func buildContext() (*ctx, error) {
	s := schema.Schema()
	c := &ctx{
		SurfaceCount: len(s.SurfaceCatalog),
		RecipeCount:  len(recipes.List()),
	}

	// Stable order: encoding surfaces first (alphabetical), then layouts.
	var encNames, layoutNames []string
	for name, def := range s.SurfaceCatalog {
		if def.Kind == "encoding" {
			encNames = append(encNames, name)
		} else if def.Kind == "layout" {
			layoutNames = append(layoutNames, name)
		}
	}
	sort.Strings(encNames)
	sort.Strings(layoutNames)

	for _, n := range encNames {
		row, err := buildSurfaceRow(n, s.SurfaceCatalog[n])
		if err != nil {
			return nil, err
		}
		c.Encodings = append(c.Encodings, row)
	}
	for _, n := range layoutNames {
		row, err := buildSurfaceRow(n, s.SurfaceCatalog[n])
		if err != nil {
			return nil, err
		}
		c.Layouts = append(c.Layouts, row)
	}

	// Operators — sorted by name
	var opNames []string
	for n := range s.Operators {
		opNames = append(opNames, n)
	}
	sort.Strings(opNames)
	for _, n := range opNames {
		op := s.Operators[n]
		ex, err := prettyJSON(op.Example)
		if err != nil {
			return nil, fmt.Errorf("operator %s example: %w", n, err)
		}
		c.Operators = append(c.Operators, operatorRow{
			Name:    n,
			Args:    op.Args,
			Doc:     op.Doc,
			Example: ex,
		})
	}

	// Presentation notes — convert key→Body to Title→Body rows; key becomes
	// the Title in start-case, with underscores → spaces.
	var noteKeys []string
	for k := range s.PresentationNote {
		noteKeys = append(noteKeys, k)
	}
	sort.Strings(noteKeys)
	for _, k := range noteKeys {
		c.PresentationNotes = append(c.PresentationNotes, noteRow{
			Title: titleFromKey(k),
			Body:  s.PresentationNote[k],
		})
	}

	return c, nil
}

func buildSurfaceRow(name string, def schema.SurfaceDef) (surfaceRow, error) {
	row := surfaceRow{
		Name:   name,
		Usage:  def.Usage,
		Fields: def.Fields,
	}
	examples := schema.ExamplesFor(name)
	if len(examples) > 0 {
		ex, err := prettyJSON(examples[0])
		if err != nil {
			return row, fmt.Errorf("surface %s example: %w", name, err)
		}
		row.Example = ex
	}
	return row, nil
}

// ─── helpers ────────────────────────────────────────────────────────────

func renderOne(name string, data *ctx) (string, error) {
	body, err := templates.ReadFile("templates/" + name)
	if err != nil {
		return "", err
	}
	tmpl, err := template.New(name).Parse(string(body))
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func prettyJSON(raw json.RawMessage) (string, error) {
	if len(raw) == 0 {
		return "", nil
	}
	var buf bytes.Buffer
	if err := json.Indent(&buf, raw, "", "  "); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func titleFromKey(k string) string {
	parts := strings.Split(k, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, " ")
}
