import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(here, '..', '..')
const schemaPath = resolve(repoRoot, 'internal/schema/schema.json')
const outPath = resolve(repoRoot, 'template/src/generated/catalog.js')

const schema = JSON.parse(readFileSync(schemaPath, 'utf8'))
const catalog = schema['x-surface-catalog']

if (!catalog || typeof catalog !== 'object' || Array.isArray(catalog)) {
  throw new Error('schema missing x-surface-catalog object')
}

const rows = Object.entries(catalog)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([name, def]) => {
    if (!def || typeof def.kind !== 'string' || typeof def.binds !== 'string') {
      throw new Error(`surface ${name} missing kind/binds`)
    }
    return `  ${JSON.stringify(name)}: { kind: ${JSON.stringify(def.kind)}, binds: ${JSON.stringify(def.binds)} }`
  })

mkdirSync(dirname(outPath), { recursive: true })
writeFileSync(outPath, [
  '// AUTO-GENERATED by template/scripts/generate-catalog.mjs. Do not edit.',
  '// Source: internal/schema/schema.json x-surface-catalog.',
  'export const CATALOG = Object.freeze({',
  rows.join(',\n'),
  '})',
  '',
].join('\n'))
